# Generated by Django 2.0.5 on 2019-01-15 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('con_ins', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authgrouppermissions',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='authgrouppermissions',
            name='group',
        ),
        migrations.RemoveField(
            model_name='authgrouppermissions',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='authpermission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='authpermission',
            name='content_type',
        ),
        migrations.AlterUniqueTogether(
            name='authusergroups',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='authusergroups',
            name='group',
        ),
        migrations.RemoveField(
            model_name='authusergroups',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='authuseruserpermissions',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='authuseruserpermissions',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='authuseruserpermissions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='djangoadminlog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='djangoadminlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
    ]
