# Generated by Django 2.0.5 on 2019-01-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con_ins', '0002_auto_20190115_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_s', models.CharField(max_length=100)),
                ('statut_s', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuts', models.IntegerField(choices=[(1, 'Commercial'), (2, 'Magasin')], default=1)),
            ],
        ),
    ]
