# Generated by Django 2.1.5 on 2019-01-16 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('con_ins', '0003_session_utilisateur_statut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='client',
            name='idlocalisation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='idmagasinvdsa',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='idclient',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='idcommercial',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='idsousfamille',
        ),
        migrations.RemoveField(
            model_name='magasinvdsa',
            name='idlocalisation',
        ),
        migrations.DeleteModel(
            name='Session_utilisateur',
        ),
        migrations.RemoveField(
            model_name='sousfamille',
            name='idfamille',
        ),
        migrations.DeleteModel(
            name='Statut',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Commercial',
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
        migrations.DeleteModel(
            name='Famille',
        ),
        migrations.DeleteModel(
            name='Localisation',
        ),
        migrations.DeleteModel(
            name='Magasinvdsa',
        ),
        migrations.DeleteModel(
            name='Sousfamille',
        ),
    ]
