# Generated by Django 2.1.3 on 2019-01-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backoffice', '0004_myfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFile',
        ),
    ]
