# Generated by Django 2.1.3 on 2019-01-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Geolocalisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('mdp', models.CharField(max_length=64)),
                ('nom', models.CharField(blank=True, max_length=64, null=True)),
                ('prenom', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('date_inscription', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64)),
                ('mdp', models.CharField(max_length=64)),
                ('nom', models.CharField(blank=True, max_length=64, null=True)),
                ('prenom', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'Commercial',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('marge', models.DecimalField(decimal_places=2, max_digits=11)),
                ('idmagasinvdsa', models.CharField(db_column='idMagasinVDSA', max_length=1)),
                ('idclient', models.ForeignKey(db_column='idClient', on_delete=django.db.models.deletion.DO_NOTHING, to='Geolocalisation.Client')),
                ('idcommercial', models.ForeignKey(db_column='idCommercial', on_delete=django.db.models.deletion.DO_NOTHING, to='Geolocalisation.Commercial')),
            ],
            options={
                'db_table': 'Facture',
            },
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'Famille',
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.PositiveIntegerField()),
                ('ville', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'Localisation',
            },
        ),
        migrations.CreateModel(
            name='Magasinvdsa',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nom_magasin', models.CharField(max_length=64)),
                ('email_directeur', models.CharField(blank=True, max_length=64, null=True)),
                ('mdp_directeur', models.CharField(blank=True, max_length=64, null=True)),
                ('nom_directeur', models.CharField(blank=True, max_length=64, null=True)),
                ('prenom_directeur', models.CharField(blank=True, max_length=64, null=True)),
                ('idlocalisation', models.ForeignKey(db_column='idLocalisation', on_delete=django.db.models.deletion.DO_NOTHING, to='Geolocalisation.Localisation')),
            ],
            options={
                'db_table': 'MagasinVDSA',
            },
        ),
        migrations.CreateModel(
            name='Sousfamille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=64, null=True)),
                ('idfamille', models.ForeignKey(blank=True, db_column='idFamille', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Geolocalisation.Famille')),
            ],
            options={
                'db_table': 'SousFamille',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='facture',
            name='idsousfamille',
            field=models.ForeignKey(blank=True, db_column='idSousFamille', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Geolocalisation.Sousfamille'),
        ),
        migrations.AddField(
            model_name='client',
            name='idlocalisation',
            field=models.ForeignKey(blank=True, db_column='idLocalisation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Geolocalisation.Localisation'),
        ),
        migrations.AddField(
            model_name='client',
            name='idmagasinvdsa',
            field=models.ForeignKey(db_column='idMagasinVDSA', on_delete=django.db.models.deletion.DO_NOTHING, to='Geolocalisation.Magasinvdsa'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('id', 'idmagasinvdsa')},
        ),
    ]
